const Politica = () => {
    return (
        <div>
           Responsable de las bases de datos: MARKETING PROCESOS Y GESTIÓN S.A. MAPROGES S.A
Domicilio: / Bogotá - Colombia
Correo electrónico: prensa@eldeportivo.com.co
Teléfono: (57) 6109565 EXT 129
Para MARKETING PROCESOS Y GESTIÓN S.A. MAPROGES S.A., en lo sucesivo y para los efectos de este documento EL DEPORTIVO, empresa comprometida con el más estricto cumplimiento de la ley y la protección de los derechos de las personas, y de todos nuestros usuarios es muy importante la conservación, preservación, protección e integridad de los datos personales que usted ha puesto a nuestra disposición. Por esta razón, hemos diseñado estas políticas de almacenamiento, tratamiento y uso de sus datos personales.

I. DISPOSICIONES GENERALES

ARTÍCULO 1. LEGISLACIÓN APLICABLE. Este documento y la política que se plantea fue elaborado de conformidad con los mandatos de la Constitución Política de Colombia (arts. 15 y 20), la Ley 1581 de 2012 "por la cual se dictan disposiciones generales para la protección de datos personales" y el Decreto 1377 de 2013 "por el cual se reglamenta parcialmente la Ley 1581 de 2012", por tratarse de una empresa colombiana, pero su alcance y ámbito de aplicación se extiende a todos los territorios en los que se hagan descargas de contenido, se visualice información generada por EL DEPORTIVO y por tanto serán aplicables las normas locales que se compaginen con las normas antes citadas.

ARTÍCULO 2. ÁMBITO DE APLICACIÓN. Este documento aplica para el tratamiento de los datos personales que obtenga y administre EL DEPORTIVO. Igualmente, aplica para el tratamiento de los datos personales que obtengan sus agentes comerciales, distribuidores, filiales, subordinadas y los desarrolladores de contenido, que son tratados por EL DEPORTIVO en su condición de centralizador y administrador de todas sus bases de datos.

ARTÍCULO 3. BASES DE DATOS. Las políticas y procedimientos contenidos en el presente documento aplican para las bases de datos de CONSUMIDORES, USUARIOS, COMPRADORES, USUARIOS DE LOS PORTALES WEB DE PROPIEDAD DE EL DEPORTIVO QUE ESTA SOCIEDAD ADMINISTRA; CONSUMIDORES PARTICIPANTES EN SORTEOS, CONCURSOS O ACTIVIDADES PROMOCIONALES; USUARIOS DE LAS FAN PAGE EN EL SITIO FACEBOOK DE LAS MARCAS Y PRODUCTOS QUE TENGA EL DEPORTIVO.; SEGUIDORES DE LA(S) CUENTA(S) EN TWITTER QUE TENGA EL DEPORTIVOO SUS MARCAS Y PRODUCTOS; SEGUIDORES O CONTACTOS DE CUALQUIER CUENTA EN CUALQUIER RED SOCIAL QUE TENGA EL DEPORTIVO.

Estas políticas y manual de tratamiento aplicarán también para los datos personales de clientes, proveedores y trabajadores, cuando el contacto que se haga o el tratamiento de sus datos escape del ámbito propio de la relación comercial y laboral que se mantiene con ellos, respectivamente.

ARTÍCULO 4. OBJETO. Por medio del presente manual se da cumplimiento a lo previsto en el literal k) del artículo 17 y en el literal f) del artículo 18 de la Ley 1581 de 2012, que regulan los deberes que asisten a los responsables y encargados del tratamiento de datos personales, así como a lo dispuesto en el Capítulo Tercero del Decreto 1377 de 2013 sobre "Políticas de Tratamiento", dentro de los cuales se encuentra la obligación de adoptar un manual interno de políticas y procedimientos para garantizar el adecuado cumplimiento de la ley, en especial para la atención de consultas y reclamos, y velar porque los Encargados del Tratamiento lo cumplan. Igualmente, este documento tiene el objeto de regular los procedimientos de recolección, almacenamiento y tratamiento de los datos de carácter personal que realizan EL DEPORTIVO y/o sus marcas, a fin de garantizar y proteger el derecho fundamental de habeas data que tienen todas las personas naturales.

ARTÍCULO 5. DEFINICIONES. Para efectos de la aplicación de las reglas contenidas en el presente manual, y de acuerdo con lo establecido en el artículo 3 de la Ley 1581 de 2012, se entiende por: a) Autorización: consentimiento previo, expreso e informado del Titular para llevar a cabo el Tratamiento de datos personales; b) Aviso de privacidad: documento físico, electrónico o en cualquier otro formato generado por el Responsable que se pone a disposición del Titular para el tratamiento de sus datos personales. En el Aviso de Privacidad se comunica al Titular la información relativa a la existencia de las políticas de tratamiento de información que le serán aplicables, la forma de acceder a las mismas y las características del tratamiento que se pretende dar a los datos personales; c) Base de datos: conjunto organizado de datos personales que sea objeto de Tratamiento; d) Dato personal: cualquier información vinculada o que pueda asociarse a una o varias personas naturales determinadas o determinables; e) Dato privado: es aquel que por su naturaleza íntima o reservada sólo es relevante para el Titular. f) Datos sensibles: aquellos que afectan la intimidad del Titular o cuyo uso indebido puede generar su discriminación, tales como aquellos que revelen el origen racial o étnico, la orientación política, las convicciones religiosas o filosóficas, la pertenencia a sindicatos, organizaciones sociales o de derechos humanos, o que promueva intereses de cualquier partido político o que garanticen los derechos y garantías de partidos políticos de oposición, así como los datos relativos a la salud, a la vida sexual y los datos biométricos; g) Encargado del Tratamiento: persona natural o jurídica, pública o privada, que por sí misma o en asocio con otros realice el Tratamiento de datos personales por cuenta del Responsable del Tratamiento; h) Responsable del Tratamiento: persona natural o jurídica, pública o privada, que por sí misma o en asocio con otros decida sobre la base de datos y/o el Tratamiento de los datos; i) Titular: persona natural cuyos datos personales sean objeto de Tratamiento; j) Tratamiento: cualquier operación o conjunto de operaciones sobre datos personales, tales como la recolección, almacenamiento, uso, circulación o supresión de los mismos.

ARTÍCULO 6. PRINCIPIOS. Los principios que se establecen a continuación constituyen los parámetros generales que serán respetados por EL DEPORTIVO en los procesos de acopio, uso y tratamiento de datos personales; a) Principio de finalidad: el Tratamiento de los datos personales recogidos por EL DEPORTIVO debe obedecer a una finalidad legítima de la cual debe ser informado el Titular; b) Principio de libertad: el Tratamiento sólo puede llevarse a cabo con el consentimiento previo, expreso e informado del Titular. Los datos personales no podrán ser obtenidos o divulgados sin previa autorización, o en ausencia de mandato legal o judicial que releve el consentimiento; c) Principio de veracidad o calidad: la información sujeta a Tratamiento debe ser veraz, completa, exacta, actualizada, comprobable y comprensible. Se prohíbe el Tratamiento de datos parciales, incompletos, fraccionados o que induzcan a error; d) Principio de transparencia: en el Tratamiento debe garantizarse el derecho del Titular a obtener de EL DEPORTIVO en cualquier momento y sin restricciones, información acerca de la existencia de datos que le conciernan; e) Principio de acceso y circulación restringida: los datos personales, salvo la información pública, no podrán estar disponibles en Internet u otros medios de divulgación o comunicación masiva, salvo que el acceso sea técnicamente controlable para brindar un conocimiento restringido sólo a los Titulares o terceros autorizados; f) Principio de seguridad: la información sujeta a Tratamiento por parte de EL DEPORTIVO se deberá proteger mediante el uso de las medidas técnicas, humanas y administrativas que sean necesarias para otorgar seguridad a los registros evitando su adulteración, pérdida, consulta, uso o acceso no autorizado o fraudulento; g) Principio de confidencialidad: todas las personas que intervengan en el Tratamiento de datos personales están obligadas a garantizar la reserva de la información, inclusive después de finalizada su relación con alguna de las labores que comprende el Tratamiento.

CAPÍTULO II - AUTORIZACIÓN

ARTÍCULO 7. AUTORIZACIÓN. La recolección, almacenamiento, uso, circulación o supresión de datos personales por parte de EL DEPORTIVO y/o sus marcas requiere del consentimiento libre, previo, expreso e informado del titular de los mismos. EL DEPORTIVO, en su condición de responsable del tratamiento de datos personales contenidos en sus bases de datos y/o de sus marcas, ha dispuesto de los mecanismos necesarios para obtener la autorización de los titulares, garantizando en todo caso que sea posible verificar el otorgamiento de dicha autorización.

RTÍCULO 8. FORMA Y MECANISMOS PARA OTORGAR LA AUTORIZACIÓN. A La autorización puede constar en un documento físico, electrónico, formulario, en un archivo de audio o en cualquier otro formato existente o por existir que permita garantizar su posterior consulta. El contenido de la autorización otorgada para la recolección y tratamiento del dato será emitido por EL DEPORTIVO y será puesta a disposición del Titular previo al Tratamiento de sus datos personales, de conformidad con lo que establece la Ley 1581 de 2102.

Con el procedimiento de autorización consentida se garantiza que se ha puesto en conocimiento del titular de los datos personales, tanto el hecho de que su información personal será recogida y utilizada para fines determinados y conocidos, como que tiene la opción de conocer cualquier alteración a los mismos y el uso específico que de ellos se ha dado. Lo anterior con el fin de que el Titular tome decisiones informadas con relación a sus datos personales y tenga control sobre el uso que se hace de su información personal.

La autorización que en todo caso solicitarán EL DEPORTIVO al titular del dato es una declaración que lo informa sobre: a) Quién recopila el dato (responsable o encargado); b) Qué datos recopila; c) Para qué recoge los datos (las finalidades del tratamiento); d) Cómo ejercer derechos de acceso, corrección, actualización o supresión de los datos personales suministrados; e) Si se recopilan datos sensibles, y la posibilidad de no darlos a conocer.

RTÍCULO 9. PRUEBA DE LA AUTORIZACIÓN.A EL DEPORTIVO adoptará todas las medidas necesarias para mantener registros de la obtención de autorización por parte de los titulares de datos personales para el tratamiento de los mismos.

RTÍCULO 10. AVISO DE PRIVACIDAD:A El Aviso de Privacidad es el documento físico, electrónico o en cualquier otro formato, que es puesto a disposición del Titular para el tratamiento de sus datos personales. A través de este documento se comunica al Titular la información relativa a la existencia de las políticas de tratamiento de información que le serán aplicables, la forma de acceder a las mismas y las características del tratamiento que se pretende dar a los datos personales. El Aviso de Privacidad de EL DEPORTIVO está disponible, entre otros medios, en la página web www.eldeportivo.com.co

ARTÍCULO 11. CONTENIDO MÍNIMO DEL AVISO DE PRIVACIDAD. El Aviso de Privacidad, como mínimo, deberá contener la siguiente información: A. La identidad, domicilio y datos de contacto del Responsable del Tratamiento; B. El tipo de tratamiento al cual serán sometidos los datos y la finalidad del mismo, y C. Los mecanismos generales dispuestos por el Responsable para que el Titular conozca la política de tratamiento de la información y los cambios sustanciales que se produzcan en ella. En todos los casos, debe informar al Titular cómo acceder o consultar la política de tratamiento de información.

ARTÍCULO 12. AVISO DE PRIVACIDAD Y LAS POLÍTICAS DE TRATAMIENTO DE LA INFORMACIÓN. EL DEPORTIVO conservará el modelo del Aviso de Privacidad que se transmitió a los Titulares mientras se lleve a cabo tratamiento de datos personales y perduren las obligaciones que de este deriven. Para el almacenamiento del modelo, EL DEPORTIVO podrá emplear medios informáticos, electrónicos o cualquier otra tecnología.

CAPÍTULO III - DERECHOS Y DEBERES

ARTÍCULO 13. DERECHOS DE LOS TITULARES DE LA INFORMACIÓN. De conformidad con lo dispuesto en el artículo 8 de la Ley 1581 de 2012, el titular de datos personales tiene los siguientes derechos: a) Conocer, actualizar y rectificar sus datos personales frente a EL DEPORTIVO, en su condición de Responsable y Encargado del Tratamiento; b) Solicitar prueba de la autorización otorgada a EL DEPORTIVO, en su condición de Responsable y Encargado del Tratamiento; c) Ser informado por EL DEPORTIVO, previa solicitud, respecto del uso que le ha dado a sus datos personales; d) Presentar ante la Superintendencia de Industria y Comercio quejas por infracciones a lo dispuesto en la Ley 1581 de 2012, una vez haya agotado el trámite de consulta o reclamo ante el Responsable del Tratamiento; e) Revocar la autorización y/o solicitar la supresión del dato cuando en el Tratamiento no se respeten los principios, derechos y garantías constitucionales y legales; f) Acceder en forma gratuita a sus datos personales que hayan sido objeto de Tratamiento.

ARTÍCULO 14. DEBERES EN RELACIÓN CON EL TRATAMIENTO DE LOS DATOS PERSONALES. EL DEPORTIVO tendrá presente, en todo momento, que los datos personales son propiedad de las personas naturales a las que se refieren y que sólo ellas pueden decidir sobre los mismos. En este sentido, hará uso de ellos sólo para aquellas finalidades para las que se encuentra facultado debidamente en la autorización obtenida al momento de recabar el dato, y respetando en todo momento los mandatos de la Constitución, la Ley 1581 de 2012 sobre protección de datos personales y el Decreto 1377 de 2013 que la reglamenta.De conformidad con lo establecido en el artículo 17 de la Ley 1581 de 2012, EL DEPORTIVO se compromete a cumplir en forma permanente con los siguientes deberes en lo relacionado con en el tratamiento de datos personales: a) Garantizar al Titular, en todo tiempo, el pleno y efectivo ejercicio del derecho de habeas data; b) Conservar la información bajo las condiciones de seguridad necesarias para impedir su adulteración, pérdida, consulta, uso o acceso no autorizado o fraudulento; c) Realizar oportunamente, esto es, en los términos previstos en los artículos 14 y 15 de la Ley 1581 de 2012, la actualización, rectificación o supresión de los datos; d) Tramitar las consultas y los reclamos formulados por los Titulares en los términos señalados en el artículo 14 de la Ley 1581 de 2012; e) Insertar en la base de datos la leyenda "información en discusión judicial" una vez notificado por parte de la autoridad competente sobre procesos judiciales relacionados con la calidad o detalles del dato personal; f) Abstenerse de circular información que esté siendo controvertida por el Titular y cuyo bloqueo haya sido ordenado por la Superintendencia de Industria y Comercio; g) Permitir el acceso a la información únicamente a las personas que pueden tener acceso a ella; h) Informar a la Superintendencia de Industria y Comercio cuando se presenten violaciones a los códigos de seguridad y existan riesgos en la administración de la información de los Titulares; i) Cumplir las instrucciones y requerimientos que imparta la Superintendencia de Industria y Comercio.

CAPÍTULO IV - PROCEDIMIENTOS DE ACCESO, CONSULTA Y RECLAMACIÓN La Ley 1581 de 2012 confiere a todas las personas naturales unos derechos y garantías que buscan dotarlos de herramientas para proteger sus datos personales y el uso que se les da a estos. Todo derecho que pretenda ser efectivo debe contar con un mecanismo conocido y eficiente mediante el cual se pueda hacer valer.
A continuación EL DEPORTIVO le presenta los derechos que puede hacer valer ante nosotros, en su condición de titular de la información, y los mecanismos que tenemos a su disposición para ello.

ARTÍCULO 15. DERECHO DE ACCESO: El poder de disposición o decisión que tiene el Titular sobre la información de la que es titular implica el derecho de acceder y conocer si su información personal está siendo objeto de Tratamiento, así como su alcance. EL DEPORTIVO garantiza al Titular su derecho de acceso de la siguiente forma: a) El titular de la información podrá conocer, si lo solicita, si efectivamente su(s) dato(s) está(n) siendo tratado(s) por EL DEPORTIVO; b) El Titular podrá tener acceso a sus datos personales que estén en posesión del responsable; c) EL DEPORTIVO y/o Las Sociedades informarán al Titular, en el momento de obtener su información, sobre el tipo de datos personales tratados y todas y cada una de las finalidades que justifican el Tratamiento.

PARÁGRAFO: EL DEPORTIVO garantizará el derecho de acceso, previa acreditación de la identidad del Titular o personalidad de su representante, poniendo a disposición de este, de manera gratuita, el detalle de sus datos personales a través de medios físicos o electrónicos que permitan el acceso directo del Titular a ellos, de forma que el Titular pueda hacer efectivo su derecho de rectificar, corregir o solicitar la supresión de todos sus datos o de parte de estos.

ARTÍCULO 16. CONSULTAS. De conformidad con lo establecido en el artículo 14 de la Ley 1581 de 2012, los titulares o sus causahabientes podrán consultar la información personal del Titular que repose en cualquier base de datos. En consecuencia, EL DEPORTIVO garantizará el derecho de consulta, suministrando a estos toda la información contenida en el registro individual o que esté vinculada con la identificación del Titular.

Para la atención de solicitudes de consulta de datos personales EL DEPORTIVO garantiza:

Tener habilitada sus líneas de atención a los usuarios y/o compradores en el correo electrónico prensa@eldeportivo.com.co, y otros que considere pertinentes en su momento y que serán efectivamente anunciados mediante modificaciones a su Aviso de Privacidad.

En cualquier caso, independientemente del mecanismo implementado para la atención de solicitudes de consulta, estas serán atendidas en un término máximo de diez (10) días hábiles según el calendario colombiano, contados a partir de la fecha de su recibo. Cuando no fuere posible atender la consulta dentro de dicho término, se informará al interesado antes del vencimiento de los 10 días, expresando los motivos de la demora y señalando la fecha en que se atenderá su consulta, la cual en ningún caso podrá superar los cinco (5) días hábiles siguientes al vencimiento del primer plazo.

ARTÍCULO 17. RECLAMOS. De conformidad con lo dispuesto en el artículo 14 de la Ley 1581 de 2012, el Titular o sus causahabientes que consideren que la información contenida en una base de datos debe ser objeto de corrección, actualización o supresión, o cuando adviertan el presunto incumplimiento de cualquiera de los deberes contenidos en la Ley 1581 de 2012, podrán presentar un reclamo ante el Responsable del Tratamiento, el cual será tramitado bajo las siguientes reglas: 1) El reclamo se formulará mediante solicitud dirigida al Responsable del Tratamiento o al Encargado del Tratamiento, con la identificación del Titular, la descripción de los hechos que dan lugar al reclamo, la dirección, y con inclusión de los documentos que soporten la reclamación. Si el reclamo resulta incompleto, se requerirá al interesado dentro de los cinco (5) días siguientes a la recepción del reclamo para que subsane las fallas. Transcurridos dos (2) meses desde la fecha del requerimiento, sin que el solicitante presente la información requerida, se entenderá que ha desistido del reclamo. En caso de que EL DEPORTIVO no sea competente para resolverlo, dará traslado a quien corresponda en un término máximo de dos (2) días hábiles e informará de la situación al interesado. 2) Una vez recibido el reclamo completo, se incluirá en un término no mayor a dos (2) días hábiles, en la base de datos, una leyenda que diga "reclamo en trámite" y el motivo del mismo. Dicha leyenda deberá mantenerse hasta que el reclamo sea decidido. 3) El término máximo para atender el reclamo será de quince (15) días hábiles contados a partir del día siguiente a la fecha de su recibo. Cuando no fuere posible atenderlo dentro de dicho término, se informarán al interesado antes del vencimiento del referido plazo los motivos de la demora y la fecha en que se atenderá su reclamo, la cual en ningún caso podrá superar los ocho (8) días hábiles siguientes al vencimiento del primer término.

ARTÍCULO 18. SUPRESIÓN DE DATOS. El Titular tiene el derecho, en todo momento, de solicitar a EL DEPORTIVO la eliminación de sus datos personales cuando:

Considere que los mismos no están siendo tratados conforme a los principios, deberes y obligaciones previstas en la Ley 1581 de 2012.
Hayan dejado de ser necesarios o pertinentes para la finalidad para la cual fueron recabados.
Se haya superado el periodo necesario para el cumplimiento de los fines para los que fueron recabados.
Esta supresión implica la eliminación total o parcial de la información personal de acuerdo con lo solicitado por el Titular en los registros, archivos, bases de datos o tratamientos realizados por EL DEPORTIVO. Es importante tener en cuenta que el derecho de cancelación no es absoluto y el responsable puede negar el ejercicio del mismo en los siguientes casos:
(i) La solicitud de supresión de la información no procederá cuando el Titular tenga el deber legal o contractual de permanecer en la base de datos.
(ii) No sea posible efectuar la eliminación del dato por la orden de autoridad judicial o administrativa con competencia en el Territorio Nacional.
(iii) Los datos sean necesarios para proteger los intereses jurídicamente tutelados del Titular, o para garantizar el cumplimiento de una obligación legalmente adquirida por el Titular.
ARTÍCULO 19. IMPLEMENTACIÓN DE PROCEDIMIENTOS PARA GARANTIZAR EL DERECHO A PRESENTAR CONSULTAS Y RECLAMOS. En cualquier momento y de manera gratuita el Titular o su representante podrán solicitar a EL DEPORTIVO información sobre el uso de sus datos personales, la rectificación, actualización o supresión de estos, previa acreditación de su identidad. Los derechos aquí mencionados únicamente se podrán ejercer por: (i) El Titular o sus causahabientes, previa acreditación de su identidad. (ii) Su representante, previa acreditación de la representación.
Cuando la solicitud sea formulada por persona distinta del Titular y no se acredite que la misma actúa en representación de aquel, con el fin de proteger los datos de las personas, EL DEPORTIVO tomará el reclamo por no presentado.
Toda solicitud debe ser presentada a través de los medios habilitados por EL DEPORTIVO, señalados en el Aviso de Privacidad, y contener, como mínimo, la siguiente información:
1. El nombre y domicilio del Titular, o cualquier otro medio, como un correo electrónico, que permita comunicarle la respuesta.
2. Los documentos que acrediten la identidad o la personalidad de su representante.
3. La descripción clara y precisa de los datos personales respecto de los cuales el Titular pretende ejercer sus derechos.
EL DEPORTIVO garantiza que los medios puestos a disposición de los titulares de la información permitan dar una respuesta en los términos establecidos por la Ley 1581 de 2012.
Cada vez que EL DEPORTIVO ponga a disposición una herramienta nueva para facilitar el ejercicio de sus derechos por parte de los titulares de información o modifique las existentes, lo informará a través de su página web y en su Aviso de Privacidad.

ARTÍCULO 20. REVOCATORIA DE LA AUTORIZACIÓN. Los titulares de los datos personales pueden revocar el consentimiento al tratamiento de sus datos personales en cualquier momento, siempre y cuando no lo impida una disposición legal. El titular de la información deberá solicitar claramente si la revocación de su autorización versa sobre la totalidad de las finalidades consentidas inicialmente, esto es, que EL DEPORTIVO deba dejar de tratar por completo los datos del Titular, o si la revocación de su consentimiento recae sobre tipos de tratamiento determinados, como por ejemplo para fines publicitarios o de estudios de mercado. Con la segunda modalidad, esto es, la revocación parcial del consentimiento, se mantienen a salvo otros fines del tratamiento que el Responsable, de conformidad con la autorización otorgada, puede llevar a cabo y con los que el Titular está de acuerdo.

En vista de lo anterior, será necesario que el Titular, al momento de elevar la solicitud de revocatoria de consentimiento a EL DEPORTIVO indique en este si la revocación que pretende realizar es total o parcial. En el segundo caso, se deberá indicar con cuál tratamiento no está conforme el Titular.

CAPÍTULO V - SEGURIDAD DE LA INFORMACIÓN

ARTÍCULO 21. MEDIDAS DE SEGURIDAD. En desarrollo del principio de seguridad establecido en la Ley 1581 de 2012, EL DEPORTIVO adoptará las medidas técnicas, de su recurso humano y administrativas que sean necesarias para otorgar seguridad a los datos evitando su adulteración, pérdida, consulta, uso o acceso no autorizado o fraudulento.

ARTÍCULO 22. IMPLEMENTACIÓN DE LAS MEDIDAS DE SEGURIDAD. EL DEPORTIVO mantendrá protocolos de seguridad de obligatorio cumplimiento para sus colaboradores con acceso a los datos de carácter personal y a los sistemas de información. El procedimiento deberá considerar, como mínimo, los siguientes aspectos:

a) Especificación detallada de las bases de datos a las que aplica.

b) Medidas, normas, procedimientos, reglas y estándares encaminados a garantizar el nivel de seguridad exigido en la Ley 1581 de 2012.

c) Funciones y obligaciones del personal.

d) Estructura de las bases de datos de carácter personal y descripción de los sistemas de información que los tratan.

e) Procedimiento de notificación, gestión y respuesta ante las incidencias.

f) Procedimientos que garanticen la conservación de las autorizaciones extendidas por los titulares de la información.

g) Controles periódicos que se deban realizar para verificar el cumplimiento de lo dispuesto en el procedimiento de seguridad que se implemente.

h) Medidas a adoptar cuando un soporte o documento vaya a ser transportado, desechado o reutilizado.

i) El procedimiento deberá mantenerse actualizado en todo momento y deberá ser revisado siempre que se produzcan cambios relevantes en el sistema de información o en la organización del mismo.

j) El contenido del procedimiento deberá adecuarse en todo momento a las disposiciones vigentes en materia de seguridad de los datos personales.

CAPÍTULO VI - DISPOSICIONES FINALES

ARTÍCULO 23. EL DEPORTIVO designa como responsables de dar trámite a las peticiones, consultas y reclamos de los titulares de la información, de las BASES DE DATOS DE EL DEPORTIVO a prensa@eldeportivo.com.co, a quienes se deberán dirigir las solicitudes cuando se hagan por medio escrito, y quienes en todo caso se encargarán de la obtención de la información y la gestión necesaria al interior de EL DEPORTIVO para dar respuesta a los Titulares que así lo soliciten.

ARTÍCULO 24. VIGENCIA. El presente documento rige a partir del 1 de FEBRERO de 2017 y hasta el momento en que expresamente se revoque o modifique.</div>
    )
}

export default Politica
